# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20181215_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
