# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20181217_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
